package com.syuct.imm.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "message".
 */
public class User {

    /** Not-null value. */
    private String Id;
    private String userId;
    private String userName;
    private String password;
    private String status;
    private java.util.Date addTime;

    public User() {
    }

    public User(String Id) {
        this.Id = Id;
    }

    public User(String Id, String userId, String userName, String password, String status, java.util.Date addTime) {
        this.Id = Id;
        this.userId = userId;
        this.userName = userName;
        this.password = password;
        this.status = status;
        this.addTime = addTime;
    }

    /** Not-null value. */
    public String getId() {
        return Id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String Id) {
        this.Id = Id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public java.util.Date getAddTime() {
        return addTime;
    }

    public void setAddTime(java.util.Date addTime) {
        this.addTime = addTime;
    }

}
