package com.syuct.imm.db.entity.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.syuct.imm.db.entity.Friends;
import com.syuct.imm.db.entity.Message;
import com.syuct.imm.db.entity.User;
import com.syuct.imm.db.entity.RecentlyChatting;

import com.syuct.imm.db.entity.dao.FriendsDao;
import com.syuct.imm.db.entity.dao.MessageDao;
import com.syuct.imm.db.entity.dao.UserDao;
import com.syuct.imm.db.entity.dao.RecentlyChattingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendsDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig recentlyChattingDaoConfig;

    private final FriendsDao friendsDao;
    private final MessageDao messageDao;
    private final UserDao userDao;
    private final RecentlyChattingDao recentlyChattingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendsDaoConfig = daoConfigMap.get(FriendsDao.class).clone();
        friendsDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        recentlyChattingDaoConfig = daoConfigMap.get(RecentlyChattingDao.class).clone();
        recentlyChattingDaoConfig.initIdentityScope(type);

        friendsDao = new FriendsDao(friendsDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        recentlyChattingDao = new RecentlyChattingDao(recentlyChattingDaoConfig, this);

        registerDao(Friends.class, friendsDao);
        registerDao(Message.class, messageDao);
        registerDao(User.class, userDao);
        registerDao(RecentlyChatting.class, recentlyChattingDao);
    }
    
    public void clear() {
        friendsDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        recentlyChattingDaoConfig.clearIdentityScope();
    }

    public FriendsDao getFriendsDao() {
        return friendsDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RecentlyChattingDao getRecentlyChattingDao() {
        return recentlyChattingDao;
    }

}
