package com.syuct.imm.db.entity.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.syuct.imm.db.entity.Friends;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FRIENDS".
*/
public class FriendsDao extends AbstractDao<Friends, Long> {

    public static final String TABLENAME = "FRIENDS";

    /**
     * Properties of entity Friends.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FriendAccount = new Property(1, String.class, "friendAccount", false, "FRIEND_ACCOUNT");
        public final static Property FriendName = new Property(2, String.class, "friendName", false, "FRIEND_NAME");
        public final static Property HeadImageNet = new Property(3, String.class, "headImageNet", false, "HEAD_IMAGE_NET");
        public final static Property HeadImageLocal = new Property(4, String.class, "headImageLocal", false, "HEAD_IMAGE_LOCAL");
        public final static Property AddTime = new Property(5, java.util.Date.class, "addTime", false, "ADD_TIME");
        public final static Property UpdateTime = new Property(6, java.util.Date.class, "updateTime", false, "UPDATE_TIME");
    }


    public FriendsDao(DaoConfig config) {
        super(config);
    }
    
    public FriendsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FRIENDS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FRIEND_ACCOUNT\" TEXT," + // 1: friendAccount
                "\"FRIEND_NAME\" TEXT," + // 2: friendName
                "\"HEAD_IMAGE_NET\" TEXT," + // 3: headImageNet
                "\"HEAD_IMAGE_LOCAL\" TEXT," + // 4: headImageLocal
                "\"ADD_TIME\" INTEGER," + // 5: addTime
                "\"UPDATE_TIME\" INTEGER);"); // 6: updateTime
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_FRIENDS_FRIEND_ACCOUNT ON \"FRIENDS\"" +
                " (\"FRIEND_ACCOUNT\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FRIENDS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Friends entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String friendAccount = entity.getFriendAccount();
        if (friendAccount != null) {
            stmt.bindString(2, friendAccount);
        }
 
        String friendName = entity.getFriendName();
        if (friendName != null) {
            stmt.bindString(3, friendName);
        }
 
        String headImageNet = entity.getHeadImageNet();
        if (headImageNet != null) {
            stmt.bindString(4, headImageNet);
        }
 
        String headImageLocal = entity.getHeadImageLocal();
        if (headImageLocal != null) {
            stmt.bindString(5, headImageLocal);
        }
 
        java.util.Date addTime = entity.getAddTime();
        if (addTime != null) {
            stmt.bindLong(6, addTime.getTime());
        }
 
        java.util.Date updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindLong(7, updateTime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Friends entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String friendAccount = entity.getFriendAccount();
        if (friendAccount != null) {
            stmt.bindString(2, friendAccount);
        }
 
        String friendName = entity.getFriendName();
        if (friendName != null) {
            stmt.bindString(3, friendName);
        }
 
        String headImageNet = entity.getHeadImageNet();
        if (headImageNet != null) {
            stmt.bindString(4, headImageNet);
        }
 
        String headImageLocal = entity.getHeadImageLocal();
        if (headImageLocal != null) {
            stmt.bindString(5, headImageLocal);
        }
 
        java.util.Date addTime = entity.getAddTime();
        if (addTime != null) {
            stmt.bindLong(6, addTime.getTime());
        }
 
        java.util.Date updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindLong(7, updateTime.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Friends readEntity(Cursor cursor, int offset) {
        Friends entity = new Friends( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // friendAccount
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // friendName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // headImageNet
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // headImageLocal
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // addTime
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)) // updateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Friends entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFriendAccount(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFriendName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHeadImageNet(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setHeadImageLocal(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAddTime(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setUpdateTime(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Friends entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Friends entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Friends entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
